# permissions for end users to edit ovncentrals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovncentral-editor-role
rules:
- apiGroups:
  - ovn-central.openstack.org
  resources:
  - ovncentrals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn-central.openstack.org
  resources:
  - ovncentrals/status
  verbs:
  - get
