# permissions for end users to view ovncentrals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovncentral-viewer-role
rules:
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncentrals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncentrals/status
  verbs:
  - get
