# permissions for end users to view ovndbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovndbcluster-viewer-role
rules:
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovndbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovndbclusters/status
  verbs:
  - get
