# permissions for end users to edit ovndbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovndbcluster-editor-role
rules:
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovndbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovndbclusters/status
  verbs:
  - get
