# permissions for end users to edit ovnservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovnserver-editor-role
rules:
- apiGroups:
  - ovn-central.openstack.org
  resources:
  - ovnservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn-central.openstack.org
  resources:
  - ovnservers/status
  verbs:
  - get
