# permissions for end users to edit ovsdbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovsdbcluster-editor-role
rules:
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovsdbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovsdbclusters/status
  verbs:
  - get
