# permissions for end users to view ovsdbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovsdbcluster-viewer-role
rules:
- apiGroups:
  - ovn-central.openstack.org
  resources:
  - ovsdbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ovn-central.openstack.org
  resources:
  - ovsdbclusters/status
  verbs:
  - get
