apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ovn-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OVNCentral is the Schema for the ovncentrals API
      displayName: OVNCentral
      kind: OVNCentral
      name: ovncentrals.ovn.openstack.org
      version: v1alpha1
    - description: OVNDBCluster is the Schema for the ovndbclusters API
      displayName: OVNDBCluster
      kind: OVNDBCluster
      name: ovndbclusters.ovn.openstack.org
      version: v1alpha1
    - description: OVNNorthd is the Schema for the ovnnorthds API
      displayName: OVNNorthd
      kind: OVNNorthd
      name: ovnnorthds.ovn.openstack.org
      version: v1alpha1
    - description: OVSDBCluster represents a raft cluster of OVSDBServers. It is the
        Schema for the ovsdbclusters API.
      displayName: OVSDBCluster
      kind: OVSDBCluster
      name: ovsdbclusters.ovn.openstack.org
      version: v1alpha1
    - description: OVSDBServer represents the storage and network identity of an ovsdb-server
        in a raft cluster. It is the Schema for the ovsdbservers API.
      displayName: OVSDBServer
      kind: OVSDBServer
      name: ovsdbservers.ovn.openstack.org
      version: v1alpha1
  description: OVN Operator
  displayName: OVN Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Network
  - Ovn
  links:
  - name: Ovn Operator
    url: https://github.com/openstack-k8s-operators/ovn-operator
  maturity: alpha
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
