apiVersion: ovn-central.openstack.org/v1alpha1
kind: OVNCentral
metadata:
  name: ovncentral-sample
spec:
  replicas: 1
  image: quay.io/mbooth/ovn-central@sha256:e5336e6f5faa04ae4215541efc22b86f75dbc7b5d1f079a1f671b14fe1992d1a
  storageSize: 1G
