apiVersion: ovn.openstack.org/v1beta1
kind: OVNDBCluster
metadata:
  name: ovndbcluster-sb-sample
spec:
  replicas: 1
  containerImage: quay.io/podified-antelope-centos9/openstack-ovn-sb-db-server:current-podified
  logLevel: info
  storageRequest: 10G
  storageClass: local-storage
  dbType: SB
