apiVersion: ovn.openstack.org/v1beta1
kind: OVNDBCluster
metadata:
  name: ovndbcluster-nb-sample
spec:
  containerImage: quay.io/podified-antelope-centos9/openstack-ovn-nb-db-server:current-podified
  logLevel: info
  storageRequest: 10G
  storageClass: local-storage
  dbType: NB
